[config]

[templates.dmsrofi]
input_path = '@REPO_ROOT@/programs/matugen/templates/rofi.rasi'
output_path = '@REPO_ROOT@/programs/matugen/generated/rofi.rasi'

[templates.dmsswaync]
input_path = '@REPO_ROOT@/programs/matugen/templates/swaync.css'
output_path = '@REPO_ROOT@/programs/matugen/generated/swaync.css'

[templates.dmsqtct]
input_path = '@REPO_ROOT@/programs/matugen/templates/qtct.conf'
output_path = '@REPO_ROOT@/programs/matugen/generated/qt5ct.conf'

[templates.dmsqtct6]
input_path = '@REPO_ROOT@/programs/matugen/templates/qtct.conf'
output_path = '@REPO_ROOT@/programs/matugen/generated/qt6ct.conf'
