cursor #d7e5e8
cursor_text_color #bbc9cc

foreground            #d7e5e8
background            #091517
selection_foreground  #bbc9cc
selection_background  #3c494b
url_color             #00daf2

color0   #091517
color1   #ffb4ab
color2   #a0cbf2
color3   #a6ccdf
color4   #004f58
color5   #254b5b
color6   #00daf2
color7   #2b3739
color8   #bbc9cc
color9   #93000a
color10  #1a4a6c
color11  #202c2e
color12  #00daf2
color13  #a0cbf2
color14  #004f58
color15  #d7e5e8
